"""Per-project fingerprint resolution for REQ-016.

Computes two identifiers that together uniquely identify a rendered artefact:

  * commit       — short hash of the project's last-touching commit
                   (`git log -1 --format=%h -- <project>/`). A `-dirty`
                   suffix is appended when the working tree under the
                   project directory has uncommitted changes.
  * template     — the installed `material-core` package version
                   (`importlib.metadata.version`).

Both fall back to `"unknown"` when the information cannot be resolved
(e.g. `git` not on PATH, not a git checkout, or running from a tarball
build). The pre-render hook calls this module via the
`matctl fingerprint --write` command.

The resolver also returns the commit date (`%cs`, ISO YYYY-MM-DD) for
human-readable display alongside the hash.
"""

from __future__ import annotations

import shutil
import subprocess
from dataclasses import dataclass
from importlib import metadata
from pathlib import Path


UNKNOWN = "unknown"


@dataclass(frozen=True)
class Fingerprint:
    commit: str
    commit_date: str
    template: str


def _git_available() -> bool:
    return shutil.which("git") is not None


def _run_git(args: list[str], cwd: Path) -> str | None:
    try:
        result = subprocess.run(
            ["git", *args],
            cwd=str(cwd),
            capture_output=True,
            text=True,
            check=False,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    if result.returncode != 0:
        return None
    return result.stdout.strip()


def _repo_root(start: Path) -> Path | None:
    out = _run_git(["rev-parse", "--show-toplevel"], start)
    if not out:
        return None
    return Path(out)


def _resolve_template_version() -> str:
    for dist in ("material-core", "material_core"):
        try:
            return metadata.version(dist)
        except metadata.PackageNotFoundError:
            continue
    return UNKNOWN


def _is_dirty(repo_root: Path, project_rel: str) -> bool:
    """True if the working tree under <project_rel>/ has uncommitted changes."""
    out = _run_git(
        ["status", "--porcelain", "--", project_rel],
        repo_root,
    )
    if out is None:
        return False
    return bool(out.strip())


def resolve(project_dir: Path) -> Fingerprint:
    """Resolve the fingerprint for `project_dir`.

    `project_dir` must be the project root (the directory holding
    `_quarto.yml` for chapters/single, or the parent of a `slides/`
    directory). Falls back to "unknown" values when git is unavailable or
    the directory is not inside a git checkout.
    """
    template = _resolve_template_version()
    if not _git_available():
        return Fingerprint(UNKNOWN, UNKNOWN, template)

    repo_root = _repo_root(project_dir)
    if repo_root is None:
        return Fingerprint(UNKNOWN, UNKNOWN, template)

    try:
        rel = project_dir.resolve().relative_to(repo_root.resolve())
    except ValueError:
        return Fingerprint(UNKNOWN, UNKNOWN, template)

    project_rel = str(rel) if str(rel) != "." else "."
    commit = _run_git(
        ["log", "-1", "--format=%h", "--", project_rel],
        repo_root,
    ) or UNKNOWN
    commit_date = _run_git(
        ["log", "-1", "--format=%cs", "--", project_rel],
        repo_root,
    ) or UNKNOWN

    if commit != UNKNOWN and _is_dirty(repo_root, project_rel):
        commit = f"{commit}-dirty"

    return Fingerprint(commit, commit_date, template)


# ---------------------------------------------------------------------------
# Output writers — _variables.yml and _fingerprint.qmd
# ---------------------------------------------------------------------------

_VARIABLES_TEMPLATE = (
    "# Generated by `matctl fingerprint --write` — do not edit by hand.\n"
    "commit: {commit}\n"
    "commit_date: {commit_date}\n"
    "template: {template}\n"
)

_COLOPHON_TEMPLATE = (
    "<!-- Generated by `matctl fingerprint --write` — do not edit by hand. -->\n"
    "\n"
    "## Colophon {{.unnumbered}}\n"
    "\n"
    "*Document fingerprint:* `{commit}` ({commit_date}) · "
    "*template* `{template}`\n"
)

_COLOPHON_DISABLED = (
    "<!-- Generated by `matctl fingerprint --write` — fingerprint disabled in"
    " projects.yml. -->\n"
)


def write_variables(target_dir: Path, fp: Fingerprint) -> Path:
    """Write `<target_dir>/_variables.yml` with the resolved values."""
    path = target_dir / "_variables.yml"
    path.write_text(
        _VARIABLES_TEMPLATE.format(
            commit=fp.commit,
            commit_date=fp.commit_date,
            template=fp.template,
        ),
        encoding="utf-8",
    )
    return path


def write_colophon(target_dir: Path, fp: Fingerprint, enabled: bool) -> Path:
    """Write `<target_dir>/_fingerprint.qmd` with the colophon block.

    When `enabled` is False, the file is written with no rendered content
    so that any `{{< include _fingerprint.qmd >}}` in the project resolves
    to nothing.
    """
    path = target_dir / "_fingerprint.qmd"
    if enabled:
        path.write_text(
            _COLOPHON_TEMPLATE.format(
                commit=fp.commit,
                commit_date=fp.commit_date,
                template=fp.template,
            ),
            encoding="utf-8",
        )
    else:
        path.write_text(_COLOPHON_DISABLED, encoding="utf-8")
    return path
