"""Group landing page generator.

Writes a minimal static `<group>/index.html` for every non-empty group,
listing its child courses and documents as links. Regenerated by matctl
on every manifest mutation that touches group membership or a child's
visible metadata.
"""

from __future__ import annotations

import html
from pathlib import Path

import click
from ruamel.yaml.comments import CommentedMap

from ._projects import dependents_of_group, find_entry


def _render_html(
    group_title: str,
    courses: list[tuple[str, str]],
    docs: list[tuple[str, str]],
) -> str:
    """Render the landing page HTML. Pure function of its inputs."""
    title_esc = html.escape(group_title, quote=True)

    def section(heading: str, entries: list[tuple[str, str]]) -> str:
        items = "\n".join(
            f'        <li><a href="./{html.escape(name, quote=True)}/"'
            f' target="_blank" rel="noopener noreferrer">'
            f"{html.escape(title, quote=True)}</a></li>"
            for name, title in entries
        )
        return (
            f"    <section>\n"
            f"      <h2>{html.escape(heading, quote=True)}</h2>\n"
            f"      <ul>\n{items}\n      </ul>\n"
            f"    </section>"
        )

    sections: list[str] = []
    if courses:
        sections.append(section("Courses", courses))
    if docs:
        sections.append(section("Documents", docs))
    sections_html = "\n".join(sections)

    style = (
        "body { font-family: system-ui, -apple-system, Segoe UI, "
        "Roboto, sans-serif; max-width: 40rem; margin: 2rem auto; "
        "padding: 0 1rem; line-height: 1.5; color: #222; }\n"
        "    h1 { font-size: 1.6rem; margin-bottom: 1.5rem; }\n"
        "    h2 { font-size: 1.1rem; margin-top: 1.5rem; "
        "border-bottom: 1px solid #ddd; padding-bottom: 0.25rem; }\n"
        "    ul { padding-left: 1.25rem; }\n"
        "    li { margin: 0.35rem 0; }\n"
        "    a { color: #0645ad; text-decoration: none; }\n"
        "    a:hover { text-decoration: underline; }"
    )

    return (
        "<!doctype html>\n"
        '<html lang="en">\n'
        "<head>\n"
        '  <meta charset="utf-8">\n'
        '  <meta name="viewport" content="width=device-width, initial-scale=1">\n'
        f"  <title>{title_esc}</title>\n"
        f"  <style>\n    {style}\n  </style>\n"
        "</head>\n"
        "<body>\n"
        "  <main>\n"
        f"    <h1>{title_esc}</h1>\n"
        f"{sections_html}\n"
        "  </main>\n"
        "</body>\n"
        "</html>\n"
    )


def regenerate_group(cwd: Path, group: str, manifest: CommentedMap) -> None:
    """(Re)generate or remove `<group>/index.html` based on manifest state.

    Callers pass the already-mutated, already-saved manifest. This function
    does not touch `projects.yml`.
    """
    entry = find_entry(manifest, group)
    if entry is None or entry.get("type") != "group":
        raise click.ClickException(
            f"cannot regenerate landing page: {group!r} is not a group"
        )

    child_names = dependents_of_group(manifest, group)
    courses: list[tuple[str, str]] = []
    docs: list[tuple[str, str]] = []
    for child_name in child_names:
        child = find_entry(manifest, child_name)
        if child is None:
            continue
        pair = (child_name, str(child.get("title", child_name)))
        if child.get("structure") == "chapters":
            courses.append(pair)
        elif child.get("structure") == "single":
            docs.append(pair)

    group_dir = cwd / group
    target = group_dir / "index.html"

    if courses or docs:
        group_dir.mkdir(exist_ok=True)
        html_text = _render_html(str(entry.get("title", group)), courses, docs)
        tmp = target.with_suffix(".html.tmp")
        tmp.write_text(html_text, encoding="utf-8")
        tmp.replace(target)
        return

    target.unlink(missing_ok=True)
    if group_dir.exists():
        try:
            group_dir.rmdir()
        except OSError:
            click.echo(
                f"warning: {group}/ not removed — directory is not empty"
            )
